In [2]:
import pandas as pd
import numpy as np
from datetime import datetime

In [4]:
df = pd.read_csv('../../src/data/EXTR_Lookup.csv')
pd.set_option('display.max_colwidth', 80)

In [5]:
df[df['LUType']==95]

      LUType  LUItem                                       LUDescription
1183      95       1  MODERATE
1184      95       2  HIGH
1185      95       3  EXTREME

In [6]:
df.head()

   LUType  LUItem                                       LUDescription
0       1       1  LAND ONLY
1       1      10  Land with new building
2       1      11  Household, single family units
3       1      12  Multiple family residence (Residential, 2-4 units)
4       1      13  Multiple family residence (Residential, 5+ units)

In [20]:
df1 = pd.read_csv('../data/EXTR_Parcel.csv', encoding='latin-1')
df1.columns

Index(['Major', 'Minor', 'PropName', 'PlatName', 'PlatLot', 'PlatBlock',
       'Range', 'Township', 'Section', 'QuarterSection', 'PropType', 'Area',
       'SubArea', 'SpecArea', 'SpecSubArea', 'DistrictName', 'LevyCode',
       'CurrentZoning', 'HBUAsIfVacant', 'HBUAsImproved', 'PresentUse',
       'SqFtLot', 'WaterSystem', 'SewerSystem', 'Access', 'Topography',
       'StreetSurface', 'RestrictiveSzShape', 'InadequateParking',
       'PcntUnusable', 'Unbuildable', 'MtRainier', 'Olympics', 'Cascades',
       'Territorial', 'SeattleSkyline', 'PugetSound', 'LakeWashington',
       'LakeSammamish', 'SmallLakeRiverCreek', 'OtherView', 'WfntLocation',
       'WfntFootage', 'WfntBank', 'WfntPoorQuality', 'WfntRestrictedAccess',
       'WfntAccessRights', 'WfntProximityInfluence', 'TidelandShoreland',
       'LotDepthFactor', 'TrafficNoise', 'AirportNoise', 'PowerLines',
       'OtherNuisances', 'NbrBldgSites', 'Contamination', 'DNRLease',
       'AdjacentGolfFairway', 'AdjacentGreenbelt', 'HistoricSite',
       'CurrentUseDesignation', 'NativeGrowthProtEsmt', 'Easements',
       'OtherDesignation', 'DeedRestrictions', 'DevelopmentRightsPurch',
       'CoalMineHazard', 'CriticalDrainage', 'ErosionHazard', 'LandfillBuffer',
       'HundredYrFloodPlain', 'SeismicHazard', 'LandslideHazard',
       'SteepSlopeHazard', 'Stream', 'Wetland', 'SpeciesOfConcern',
       'SensitiveAreaTract', 'WaterProblems', 'TranspConcurrency',
       'OtherProblems'],
      dtype='object')

In [23]:
df1.head()

,Major,Minor,PropName,PlatName,PlatLot,PlatBlock,Range,Township,Section,QuarterSection,...,SeismicHazard,LandslideHazard,SteepSlopeHazard,Stream,Wetland,SpeciesOfConcern,SensitiveAreaTract,WaterProblems,TranspConcurrency,OtherProblems
0,889250,80,,VELKOFF JOHN ADD,8,,5,22,8,SE,...,N,N,N,N,N,N,N,N,N,N
1,736360,275,,ROBERTS JAY COUNTRY CLUB ESTATES,8,2,4,26,34,SE,...,N,N,N,N,N,N,N,N,N,N
2,600350,635,,NAGLES 2ND ADD,6,28,4,25,32,NE,...,N,N,N,N,N,N,N,N,N,N
3,635260,760,,OLD MILL POINT,TRACT I,,6,25,18,SE,...,N,N,N,N,N,N,N,N,N,N
4,333250,15,,HILLMAN CITY DIV NO. 05,3-4,1,4,24,22,SE,...,N,N,N,N,N,N,N,N,N,N

In [11]:
df2 = pd.read_csv('../data/EXTR_ResBldg.csv')
df2.head()

/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Major,Minor,BldgNbr,NbrLivingUnits,Address,BuildingNumber,Fraction,DirectionPrefix,StreetName,StreetType,...,FpMultiStory,FpFreestanding,FpAdditional,YrBuilt,YrRenovated,PcntComplete,Obsolescence,PcntNetCondition,Condition,AddnlCost
0,8400,130,1,1,215 SW 129TH ST 98146,215,,SW,129TH,ST,...,0,0,0,1942,0,0,0,0,4,0
1,8400,346,1,1,326 SW 132ND ST 98146,326,,SW,132ND,ST,...,1,0,1,1961,0,0,0,0,4,0
2,8700,121,1,1,16828 104TH AVE SE 98055,16828,,,104TH,AVE,...,0,0,0,1962,0,0,0,0,4,0
3,8700,123,1,1,16814 104TH AVE SE,16814,,,104TH,AVE,...,0,0,0,2011,0,0,0,0,3,0
4,8700,256,1,1,16836 106TH AVE SE 98055,16836,,,106TH,AVE,...,0,0,0,1947,0,0,0,0,3,0

In [8]:
df3 = pd.read_csv('../src/data/EXTR_RPSale.csv')
df3.head()

/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (1,2) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,ExciseTaxNbr,Major,Minor,DocumentDate,SalePrice,RecordingNbr,Volume,Page,PlatNbr,PlatType,...,PropertyType,PrincipalUse,SaleInstrument,AFForestLand,AFCurrentUseLand,AFNonProfitUse,AFHistoricProperty,SaleReason,PropertyClass,SaleWarning
0,2687551,138860,110,08/21/2014,245000,20140828001436,,,,,...,3,6,3,N,N,N,N,1,8,
1,1235111,664885,40,07/09/1991,0,199203161090,071,001,664885,C,...,3,0,26,N,N,N,N,18,3,11
2,2704079,423943,50,10/11/2014,0,20141205000558,,,,,...,3,6,15,N,N,N,N,18,8,18 31 51
3,2584094,403700,715,01/04/2013,0,20130110000910,,,,,...,3,6,15,N,N,N,N,11,8,18 31 38
4,3027422,213043,120,12/20/2019,560000,20191226000848,,,,,...,11,6,3,N,N,N,N,1,8,

In [9]:
df3.columns

Index(['ExciseTaxNbr', 'Major', 'Minor', 'DocumentDate', 'SalePrice',
       'RecordingNbr', 'Volume', 'Page', 'PlatNbr', 'PlatType', 'PlatLot',
       'PlatBlock', 'SellerName', 'BuyerName', 'PropertyType', 'PrincipalUse',
       'SaleInstrument', 'AFForestLand', 'AFCurrentUseLand', 'AFNonProfitUse',
       'AFHistoricProperty', 'SaleReason', 'PropertyClass', 'SaleWarning'],
      dtype='object')

In [10]:
df3.shape

(2072949, 24)

In [61]:
print(df3['DocumentDate'][0])
print(datetime.strptime(df3['DocumentDate'][0], '%m/%d/%Y').date())

08/21/2014
2014-08-21

In [11]:
60933

60933

## DELIVERABLES

<span style='color:Blue'> Blue is my favorite color.  </span>

1. <span style='color:Blue'> [DONE] </span> A public GitHub repository.
2. <span style='color:Blue'> [DONE, REDO AT END] </span> An `environment.yml` file that contains all the necessary packages needed to recreate your `linreg-env` conda environment.
    - Unlike Mod 1, we haven't not given you an `environment.yml` file. Be sure to refer [to the documentation](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html) to learn how to create and export the `linreg-env` conda environment.
3. <span style='color:Blue'> [TO DO] </span> A standalone `src/` directory that stores all relevant source code.
    - All functions have docstrings that act as [professional-quality documentation](http://google.github.io/styleguide/pyguide.html#381-docstrings). 
    - If applicable, [well documented](https://www.sqlstyle.guide/) SQL queries with appropriate single-line or multiline comments.
    - Quality linear regression model
       - Your model should avoid violating any of the assumptions of a linear regression
       - Whenever necessary, briefly explain in comments the changes made from one iteration to the next, and why you made these choices
4. <span style='color:Blue'> [TO DO] </span> A standalone `data/` directory that stores all relevant raw and processed data files
    - **Be sure to include how the data was obtained!**
    - All large files are labeled in the `.gitignore` file to avoid having them accidentally live in your commit history.
5. <span style='color:Blue'> [DONE] </span> A standalone `references/` directory that stores all relevant literature, data dictionaries, or useful references that were used to help you during the project.
    - Use this directory to store physical copies of the `.pdf` files; or
    - Create a `README.md` file that cites external resources that were used.
6. <span style='color:Blue'> [TO DO] </span> A standalone `reports/` directory that stores your `memo.md` and `presentation.pdf` files
7. <span style='color:Blue'> [DONE] </span> A standalone `notebooks/` directory that stores both your exploratory and report notebooks
    - A record of your workflow should be stored in `notebooks/exploratory`. Don't be afraid to leave in error messages, so you know what didn't work!
8. <span style='color:Blue'> [TO DO] </span> A user-focused `README.md` file that briefly covers your process, methodology and findings.
    - Someone with no context on your project should be able to use this document to understand the structure of your project, and adapt your code for their needs.
9. <span style='color:Blue'> [TO DO] </span> One final Jupyter Notebook file stored in `notebooks/report` that focuses on visualization and presentation
    - The very beginning of the notebook contains a description of the purpose of the notebook.
       - This is helpful for your future self and anyone of your colleagues that needs to view your notebook. Without this context, you’re implicitly asking your peers to invest a lot of energy to help solve your problem. Help them to jump into your project by providing them the purpose of this Jupyter Notebook.
    - Explanation of the data sources and where one can retrieve them
       - Whenever possible, link to the corresponding data dictionary
    - Custom functions and classes are imported from Python modules and are not created directly in the notebook. As soon as you have a working function in one of your exploratory notebooks, copy it over to `src` so it is reusable.
    - At least 4 meaningful data visualizations, with corresponding interpretations. All visualizations are well labeled with axes labels, a title, and a legend (when appropriate)
    - Take the time to make sure that you craft your story well, and clearly explain your process and findings in a way that clearly shows both your technical expertise and your ability to communicate your results!
10. <span style='color:Blue'> [TO DO] </span> A one-page memo stored in `reports/memo.md` written exclusively for a non-technical stakeholder.
    - This memo should describe:
       - A summary of the business problem you are trying to solve
       - Key takeaways from your solution
       - A section on next steps if you had more time (i.e. one additional week)
11. <span style='color:Blue'> [TO DO] </span> An "Executive Summary" Keynote/PowerPoint/Google Slide presentation (delivered as a PDF export) that explains what you have found.
    - Make sure to also add and commit this file as presentation.pdf of your non-technical presentation to your repository with a file name of `reports/presentation.pdf`.
    - Contain between 5-10 professional quality slides detailing:
       - A high-level overview of your methodology
       - The results you’ve uncovered
       - Any real-world recommendations you would like to make based on your findings (ask yourself--why should the executive team care about what you found? How can your findings help the company/stakeholder?)
       - Avoid technical jargon and explain results in a clear, actionable way for non-technical audiences.
    - The slides should use visualizations whenever possible, and avoid walls of text
    - All visualizations included in this presentation should also be exported as image files (e.g. with `plt.savefig`, not by taking a screenshot) and saved under `reports/figures/`

- Merge
- Determine:
    - Calculate covered size = sqft of house / sqft of lot
    - Cost per sqft
    - single family vs duplex
    - presence of a nuisance
    - building grade
    - (extra) anything specific to Seattle 
- Run the regression model for all 20 possible combinations 
- Analyze all 20 models
- Report:
    - R-squared
    - effect size
    - statistical significance
    for each of the 20 models